services:
  postgres-db:
    image: postgres:16-alpine
    container_name: bradesco-credito-db
    environment:
      POSTGRES_USER: admin_credito
      POSTGRES_PASSWORD: SenhaForteBradesco123
      POSTGRES_DB: db_credito_imobiliario
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - credito-network

  redis-cache:
    image: redis:7-alpine
    container_name: bradesco-credito-redis
    ports:
      - "6379:6379"
    networks:
      - credito-network

  rabbitmq-broker:
    image: rabbitmq:3-management-alpine
    container_name: bradesco-credito-rabbitmq
    ports:
      - "5672:5672"   # Porta de comunicação que o Java usa para enviar mensagens
      - "15672:15672" # Porta do painel visual (Dashboard) que abriremos no navegador
    environment:
      - RABBITMQ_DEFAULT_USER=admin_bradesco
      - RABBITMQ_DEFAULT_PASS=RabbitForte123
    networks:
      - credito-network

  api-app:
    build: .
    container_name: bradesco-credito-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/db_credito_imobiliario
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=rabbitmq-broker
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=admin_bradesco
      - SPRING_RABBITMQ_PASSWORD=RabbitForte123
    depends_on:
      - postgres-db
      - redis-cache
      - rabbitmq-broker
    networks:
      - credito-network

volumes:
  postgres_data:

networks:
  credito-network: