spring:
  application:
    name: credito-imobiliario

  datasource:
    url: jdbc:postgresql://localhost:5432/db_credito_imobiliario
    username: admin_credito
    password: SenhaForteBradesco123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
